version: 1
build_commands:
  - cmd: "dotnet build"
    transition: BUILD_RAN
    output_parser: dotnet
  - cmd: "dotnet build --no-restore"
    transition: BUILD_RAN
    output_parser: dotnet
test_commands:
  - cmd: "dotnet test"
    transition: TESTS_RAN
    output_parser: dotnet
