#!/usr/bin/env python3
"""Generate design/game-definition.md from data/game-definition.yaml.

YAML is the source of truth. Never edit the generated MD directly.
Run: python3 rules/tools/generate_game_definition.py
"""
import sys
import yaml
from pathlib import Path

def snake_to_title(s):
    return s.replace('_', ' ').title()

def render_section(key, value, level=2):
    heading = '#' * level
    title = snake_to_title(key)
    lines = [f'{heading} {title}', '']
    if isinstance(value, str):
        lines.append(value.strip())
    elif isinstance(value, dict):
        for sub_key, sub_val in value.items():
            lines += render_section(sub_key, sub_val, level + 1)
    lines.append('')
    return lines

def main():
    root = Path(__file__).parent.parent.parent
    yaml_path = root / 'data' / 'game-definition.yaml'
    out_path = root / 'design' / 'game-definition.md'

    with open(yaml_path) as f:
        data = yaml.safe_load(f)

    lines = [
        f"# {data.get('name', 'Pinder')} — Game Definition",
        '',
        '> **Source of truth:** `data/game-definition.yaml`  ',
        '> **Do not edit this file directly.** Regenerate with `python3 rules/tools/generate_game_definition.py`',
        '',
    ]

    # Define section order and display names
    section_order = [
        ('vision', 'Vision'),
        ('world_description', 'World Description'),
        ('texting_psychology', 'Texting Psychology'),
        ('player_role_description', 'Player Role'),
        ('opponent_role_description', 'Opponent Role'),
        ('opponent_friction', 'Opponent: Friction'),
        ('opponent_curiosity', 'Opponent: Curiosity'),
        ('meta_contract', 'Meta Contract'),
        ('writing_rules', 'Writing Rules'),
        ('revelation_over_statement', 'Revelation Over Statement'),
        ('delivery_rules', 'Delivery Rules'),
        ('conversation_arc', 'Conversation Arc'),
        ('dramatic_craft', 'Dramatic Craft'),
        ('horniness_time_modifiers', 'Horniness Time Modifiers'),
    ]

    for key, title in section_order:
        if key not in data:
            continue
        value = data[key]
        lines.append(f'## {title}')
        lines.append('')
        if isinstance(value, str):
            lines.append(value.strip())
            lines.append('')
        elif isinstance(value, dict):
            for sub_key, sub_val in value.items():
                sub_title = snake_to_title(sub_key)
                lines.append(f'### {sub_title}')
                lines.append('')
                lines.append(str(sub_val).strip())
                lines.append('')

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text('\n'.join(lines) + '\n')
    print(f'Generated: {out_path}')

if __name__ == '__main__':
    main()
