// Auto-generated from rules/extracted/rules-v3-enriched.yaml
// See: rules/tools/generate_tests.py
// Edit the YAML source, then re-run generation — do not edit this file manually.

using Xunit;
using Pinder.Core.Rolls;
using Pinder.Core.Stats;
using Pinder.Core.Conversation;
using Pinder.Core.Progression;
using Pinder.Core.Interfaces;
using Pinder.Core.Traps;

namespace Pinder.Core.Tests.RulesSpec
{
    [Trait("Category", "Rules")]
    public class RulesSpecTests
    {
        // =====================================================================
        // Helper methods for constructing RollResult fixtures
        // =====================================================================

        private static RollResult MakeFailureResult(FailureTier tier, int missMargin)
        {
            int dc = 15;
            int usedDieRoll;
            int statModifier = 0;

            if (tier == FailureTier.Legendary)
            {
                usedDieRoll = 1;
                statModifier = 0;
            }
            else
            {
                int needed = dc - missMargin;
                usedDieRoll = System.Math.Max(2, System.Math.Min(19, needed));
                statModifier = needed - usedDieRoll;
            }

            return new RollResult(
                dieRoll: usedDieRoll,
                secondDieRoll: null,
                usedDieRoll: usedDieRoll,
                stat: StatType.Charm,
                statModifier: statModifier,
                levelBonus: 0,
                dc: dc,
                tier: tier,
                activatedTrap: null,
                externalBonus: 0
            );
        }

        private static RollResult MakeSuccessResult(int beatMargin, bool isNat20 = false)
        {
            int dc = 13;
            if (isNat20)
            {
                return new RollResult(
                    dieRoll: 20, secondDieRoll: null, usedDieRoll: 20,
                    stat: StatType.Charm, statModifier: 0, levelBonus: 0,
                    dc: dc, tier: FailureTier.None, activatedTrap: null, externalBonus: 0
                );
            }
            int total = dc + beatMargin;
            int usedDieRoll = System.Math.Min(19, total);
            int statModifier = total - usedDieRoll;
            return new RollResult(
                dieRoll: usedDieRoll, secondDieRoll: null, usedDieRoll: usedDieRoll,
                stat: StatType.Charm, statModifier: statModifier, levelBonus: 0,
                dc: dc, tier: FailureTier.None, activatedTrap: null, externalBonus: 0
            );
        }

        private static RollResult MakeRiskResult(int need, bool isSuccess)
        {
            int dc = 13;
            int statModifier = dc - need;
            int usedDieRoll = isSuccess ? 19 : 2;
            var tier = isSuccess ? FailureTier.None : FailureTier.Fumble;
            return new RollResult(
                dieRoll: usedDieRoll, secondDieRoll: null, usedDieRoll: usedDieRoll,
                stat: StatType.Charm, statModifier: statModifier, levelBonus: 0,
                dc: dc, tier: tier, activatedTrap: null, externalBonus: 0
            );
        }

        // =====================================================================
        // §5 — Failure Scale (5 tests)
        // =====================================================================

        // Mutation: would catch if Fumble returned 0 or -2 instead of -1
        [Fact]
        public void Rule_S5_Fumble_MissBy1To2_NegativeOne()
        {
            var result = MakeFailureResult(FailureTier.Fumble, 2);
            Assert.Equal(-1, FailureScale.GetInterestDelta(result));
        }

        // Mutation: would catch if Misfire returned -2 instead of -1
        [Fact]
        public void Rule_S5_Misfire_MissBy3To5_NegativeOne()
        {
            var result = MakeFailureResult(FailureTier.Misfire, 4);
            Assert.Equal(-1, FailureScale.GetInterestDelta(result));
        }

        // Mutation: would catch if TropeTrap returned -1 instead of -2
        [Fact]
        public void Rule_S5_TropeTrap_MissBy6To9_NegativeTwo()
        {
            var result = MakeFailureResult(FailureTier.TropeTrap, 7);
            Assert.Equal(-2, FailureScale.GetInterestDelta(result));
        }

        // Mutation: would catch if Catastrophe returned -2 instead of -3
        [Fact]
        public void Rule_S5_Catastrophe_MissBy10Plus_NegativeThree()
        {
            var result = MakeFailureResult(FailureTier.Catastrophe, 11);
            Assert.Equal(-3, FailureScale.GetInterestDelta(result));
        }

        // Mutation: would catch if Legendary returned -3 or -5 instead of -4
        [Fact]
        public void Rule_S5_Legendary_Nat1_NegativeFour()
        {
            var result = MakeFailureResult(FailureTier.Legendary, 14);
            Assert.Equal(-4, FailureScale.GetInterestDelta(result));
        }

        // =====================================================================
        // §5 — Success Scale (4 tests)
        // =====================================================================

        // Mutation: would catch if beat-by-1-4 returned 0 or 2 instead of 1
        [Fact]
        public void Rule_S5_BeatDCBy1To4_PlusOne()
        {
            var result = MakeSuccessResult(3);
            Assert.Equal(1, SuccessScale.GetInterestDelta(result));
        }

        // Mutation: would catch if beat-by-5-9 returned +1 instead of +2
        [Fact]
        public void Rule_S5_BeatDCBy5To9_PlusTwo()
        {
            var result = MakeSuccessResult(7);
            Assert.Equal(2, SuccessScale.GetInterestDelta(result));
        }

        // Mutation: would catch if beat-by-10+ returned +2 instead of +3
        [Fact]
        public void Rule_S5_BeatDCBy10Plus_PlusThree()
        {
            var result = MakeSuccessResult(12);
            Assert.Equal(3, SuccessScale.GetInterestDelta(result));
        }

        // Mutation: would catch if Nat20 returned +3 instead of +4
        [Fact]
        public void Rule_S5_Nat20_PlusFour()
        {
            var result = MakeSuccessResult(7, isNat20: true);
            Assert.Equal(4, SuccessScale.GetInterestDelta(result));
        }

        // =====================================================================
        // §5 — Risk Tier (4 tests)
        // =====================================================================

        // Mutation: would catch if need<=5 classified as Medium instead of Safe
        [Fact]
        public void Rule_S5_RiskTier_Safe_NeedLte5()
        {
            var result = MakeRiskResult(5, true);
            Assert.Equal(RiskTier.Safe, result.RiskTier);
        }

        // Mutation: would catch if need 6-10 classified as Safe or Hard
        [Fact]
        public void Rule_S5_RiskTier_Medium_Need6To10()
        {
            var result = MakeRiskResult(8, true);
            Assert.Equal(RiskTier.Medium, result.RiskTier);
        }

        // Mutation: would catch if need 11-15 classified as Medium or Bold
        [Fact]
        public void Rule_S5_RiskTier_Hard_Need11To15()
        {
            var result = MakeRiskResult(13, true);
            Assert.Equal(RiskTier.Hard, result.RiskTier);
        }

        // Mutation: would catch if need>=16 classified as Hard instead of Bold
        [Fact]
        public void Rule_S5_RiskTier_Bold_Need16Plus()
        {
            var result = MakeRiskResult(18, true);
            Assert.Equal(RiskTier.Bold, result.RiskTier);
        }

        // =====================================================================
        // §5 — Risk Tier Bonus (4 tests)
        // =====================================================================

        // Mutation: would catch if Safe returned wrong bonus
        [Fact]
        public void Rule_S5_RiskBonus_Safe_Zero()
        {
            var result = MakeRiskResult(4, true);
            Assert.Equal(1, RiskTierBonus.GetInterestBonus(result)); // Safe now returns +1
        }

        // Mutation: would catch if Hard returned wrong bonus
        [Fact]
        public void Rule_S5_RiskBonus_Hard_PlusOne()
        {
            var result = MakeRiskResult(13, true);
            Assert.Equal(3, RiskTierBonus.GetInterestBonus(result)); // Hard now returns +3
        }

        // Mutation: would catch if Bold returned wrong bonus
        [Fact]
        public void Rule_S5_RiskBonus_Bold_PlusTwo()
        {
            var result = MakeRiskResult(18, true);
            Assert.Equal(5, RiskTierBonus.GetInterestBonus(result)); // Bold now returns +5
        }

        // Mutation: would catch if bonus was awarded on failure (Hard fail should be 0)
        [Fact]
        public void Rule_S5_RiskBonus_Failure_Zero()
        {
            var result = MakeRiskResult(13, false);
            Assert.Equal(0, RiskTierBonus.GetInterestBonus(result));
        }

        // =====================================================================
        // §6 — Interest States (10 tests)
        // =====================================================================

        // Mutation: would catch if 0 mapped to Bored instead of Unmatched
        [Fact]
        public void Rule_S6_Interest0_Unmatched()
        {
            var meter = new InterestMeter(0);
            Assert.Equal(InterestState.Unmatched, meter.GetState());
        }

        // Mutation: would catch if 1-4 mapped to Unmatched or Lukewarm instead of Bored
        [Fact]
        public void Rule_S6_Interest1To4_Bored()
        {
            Assert.Equal(InterestState.Bored, new InterestMeter(1).GetState());
            Assert.Equal(InterestState.Bored, new InterestMeter(4).GetState());
        }

        // Mutation: would catch if 5-9 mapped to Bored or Interested instead of Lukewarm
        [Fact]
        public void Rule_S6_Interest5To9_Lukewarm()
        {
            Assert.Equal(InterestState.Lukewarm, new InterestMeter(5).GetState());
            Assert.Equal(InterestState.Lukewarm, new InterestMeter(9).GetState());
        }

        // Mutation: would catch if 10-15 mapped to Lukewarm or VeryIntoIt instead of Interested
        [Fact]
        public void Rule_S6_Interest10To15_Interested()
        {
            Assert.Equal(InterestState.Interested, new InterestMeter(10).GetState());
            Assert.Equal(InterestState.Interested, new InterestMeter(15).GetState());
        }

        // Mutation: would catch if 16-20 mapped to Interested or AlmostThere instead of VeryIntoIt
        [Fact]
        public void Rule_S6_Interest16To20_VeryIntoIt()
        {
            Assert.Equal(InterestState.VeryIntoIt, new InterestMeter(16).GetState());
            Assert.Equal(InterestState.VeryIntoIt, new InterestMeter(20).GetState());
        }

        // Mutation: would catch if 21-24 mapped to VeryIntoIt or DateSecured instead of AlmostThere
        [Fact]
        public void Rule_S6_Interest21To24_AlmostThere()
        {
            Assert.Equal(InterestState.AlmostThere, new InterestMeter(21).GetState());
            Assert.Equal(InterestState.AlmostThere, new InterestMeter(24).GetState());
        }

        // Mutation: would catch if 25 mapped to AlmostThere instead of DateSecured
        [Fact]
        public void Rule_S6_Interest25_DateSecured()
        {
            var meter = new InterestMeter(25);
            Assert.Equal(InterestState.DateSecured, meter.GetState());
        }

        // Mutation: would catch if default starting interest was not 10
        [Fact]
        public void Rule_S6_StartingInterest_10()
        {
            var meter = new InterestMeter();
            Assert.Equal(10, meter.Current);
        }

        // Mutation: would catch if max was 24 or 26 instead of 25
        [Fact]
        public void Rule_S6_Interest_Max25()
        {
            var meter = new InterestMeter(20);
            meter.Apply(100);
            Assert.Equal(25, meter.Current);
        }

        // Mutation: would catch if min was 1 or -1 instead of 0
        [Fact]
        public void Rule_S6_Interest_Min0()
        {
            var meter = new InterestMeter(5);
            meter.Apply(-100);
            Assert.Equal(0, meter.Current);
        }

        // =====================================================================
        // §7 — Shadow Thresholds (4 tests)
        // =====================================================================

        // Mutation: would catch if shadow<6 returned tier 1 instead of 0
        [Fact]
        public void Rule_S7_Shadow_Below6_Tier0()
        {
            Assert.Equal(0, ShadowThresholdEvaluator.GetThresholdLevel(5));
        }

        // Mutation: would catch if shadow 6-11 returned tier 0 or 2 instead of 1
        [Fact]
        public void Rule_S7_Shadow_6To11_Tier1()
        {
            Assert.Equal(1, ShadowThresholdEvaluator.GetThresholdLevel(6));
            Assert.Equal(1, ShadowThresholdEvaluator.GetThresholdLevel(11));
        }

        // Mutation: would catch if shadow 12-17 returned tier 1 or 3 instead of 2
        [Fact]
        public void Rule_S7_Shadow_12To17_Tier2()
        {
            Assert.Equal(2, ShadowThresholdEvaluator.GetThresholdLevel(12));
            Assert.Equal(2, ShadowThresholdEvaluator.GetThresholdLevel(17));
        }

        // Mutation: would catch if shadow 18+ returned tier 2 instead of 3
        [Fact]
        public void Rule_S7_Shadow_18Plus_Tier3()
        {
            Assert.Equal(3, ShadowThresholdEvaluator.GetThresholdLevel(18));
            Assert.Equal(3, ShadowThresholdEvaluator.GetThresholdLevel(30));
        }

        // =====================================================================
        // §10 — Progression / LevelTable (6 tests)
        // =====================================================================

        // Mutation: would catch if 0 XP returned level 0 instead of 1
        [Fact]
        public void Rule_S10_XP0_Level1()
        {
            Assert.Equal(1, LevelTable.GetLevel(0));
        }

        // Mutation: would catch if 50 XP returned level 1 instead of 2
        [Fact]
        public void Rule_S10_XP50_Level2()
        {
            Assert.Equal(2, LevelTable.GetLevel(50));
        }

        // Mutation: would catch if 150 XP returned level 2 instead of 3
        [Fact]
        public void Rule_S10_XP150_Level3()
        {
            Assert.Equal(3, LevelTable.GetLevel(150));
        }

        // Mutation: would catch if 3500 XP returned level 10 instead of 11
        [Fact]
        public void Rule_S10_XP3500_Level11()
        {
            Assert.Equal(11, LevelTable.GetLevel(3500));
        }

        // Mutation: would catch if level 1 bonus was not 0
        [Fact]
        public void Rule_S10_LevelBonus_L1_Zero()
        {
            Assert.Equal(0, LevelTable.GetBonus(1));
        }

        // Mutation: would catch if level 5 bonus was 1 or 3 instead of 2
        [Fact]
        public void Rule_S10_LevelBonus_L5_Two()
        {
            Assert.Equal(2, LevelTable.GetBonus(5));
        }

        // =====================================================================
        // §7/§11 — Qualitative / LLM rules (17 skipped tests)
        // =====================================================================

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Dread_T1() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Dread_T2() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Dread_T3() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Fixation_T1() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Fixation_T2() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Fixation_T3() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Denial_T1() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Denial_T2() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Denial_T3() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Madness_T1() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Madness_T2() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S7_ShadowTaint_Madness_T3() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S5_Failure_Fumble_Narrative() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S5_Failure_Catastrophe_Narrative() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S5_Failure_Legendary_Narrative() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S6_Ghost_Trigger_Narrative() { }

        [Fact(Skip = "Qualitative/LLM rule — not unit-testable")]
        public void Rule_S11_LLM_Prompt_Taint_Injection() { }
    }
}
